baseURL: "https://hesed-server.web.app"
languageCode: en-us
defaultContentLanguage: en-us
title: "Hesed Server"
enableRobotsTXT: true
enableEmoji: true
theme: hugo-theme-luna
timeZone: Africa/Accra

# use git commit log to generate lastmod record
enableGitInfo: true
hasCJKLanguage: false
paginate: 5

permalinks:
  posts: /:year/:month/:day/:slug.html # 2019/01/01/hello-world.html
  pages: /:slug.html # about.html

author:
  name: Hesed

frontmatter:
  lastmod:
    - :git
    - lastmod
    - :fileModTime
    - date
    - publishDate
    - :default

taxonomies:
  tag: "tags"
  categories: "categories"

canonifyURLs: false
relativeURLs: false

imaging:
  resampleFilter: CatmullRom
  quality: 95
  anchor: smart

caches:
  getresource:
    dir: :resourceDir/_gen
    maxAge: 1000h

privacy:
  googleAnalytics:
    anonymizeIP: true
  youtube:
    privacyEnhanced: true

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

# all supported pages
$menuMain:
  - &mainMenuHome
    name: Home
    weight: 10
    identifier: home
    params:
      icon: eva eva-home
    url: /
  - &mainMenuAbout
    name: About
    weight: 20
    identifier: about
    params:
      icon: eva eva-heart
    url: /about/
  - &mainMenuLinks
    name: Links
    weight: 30
    identifier: links
    params:
      icon: eva eva-people
    url: /links/
  - &mainMenuArchives
    name: Archives
    weight: 40
    identifier: archives
    params:
      icon: eva eva-bar-chart
    url: /archives/
  - &mainMenuTags
    name: Tags
    weight: 50
    identifier: tags
    params:
      icon: eva eva-hash
    url: /tags/
  - &mainMenuSearch
    name: Search
    weight: 999
    identifier: search
    params:
      icon: eva eva-search
    url: /search/

# If you don't want the navbar, you can delete this paragraph
menu:
  main:
    - *mainMenuHome
    - *mainMenuAbout
    - *mainMenuLinks
    - *mainMenuArchives
    - *mainMenuTags
    - *mainMenuSearch

markup:
  highlight:
    style: dracula
    guessSyntax: true
    tabWidth: 4
    lineNumbersInTable: true
    lineNos: true
    codeFences: true
  goldmark:
    renderer:
      unsafe: true # enable html in markdown

# .Site.Params
params:
  publicCDN: "" # e.g. https://cdn.jsdelivr.net/gh/{{user}}/{{repo}}@latest/

  # Display title and description at the top of the page, use .Site.Title and .Site.Params.Description
  topTitle: true

  # Create a Announcement section at the top of the home page
  announcement:
    enabled: false

  # Comment system
  comments:
    enabled: false

  # RSS configuration
  rss:
    enabled: true
    fullText: true

  sitemap: true
  themeColor: "#dd6065"
  blackAndWhite: false

  # Output a nice console log
  console:
    enabled: true
    leftColor: "#dd6065"
    leftText: "Hesed Server"
    rightColor: "#feb462"
    rightText: "Powered by Hugo ❤ Luna"

  # Title counter
  headlineCounter: false

  fixedNav: false
  font: 'Roboto, "Helvetica Neue", Helvetica, Arial, sans-serif'

  customScript:
    enabled: false
    pjax: true # Auto-reload in pjax mode

  runTime:
    enabled: false

  since: "2024"

  outdatedInfoWarning:
    enabled: false

  # Automatic switching of night mode (using device settings)
  autoDarkMode: true

  share:
    twitter: true
    facebook: true
    copyLinkText: true
    qrcode: true

  qrcodeAPI: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data="

  # license
  license:
    enabled: true
    name: "CC BY-NC-ND 4.0"
    icon: "Cc-by-nc-nd.svg" # in assets folder
    url: "https://creativecommons.org/licenses/by-nc-nd/4.0"

  i18nlist: false
  imageZoom: true
  lazyload: true

  # Read English content faster, see https://bionic-reading.com/
  bionicReading:
    enabled: true
    autoBionic: false # Bionic Reading / auto enable Bionic Reading
    skipLinks: false # skip links
    excludeWords: [] # ignored words
    excludeNodeNames: [] # ignored node names

  googleTranslate: false

  pangu: false

  # enable local search plugin
  search: true

  # For outdated reminders
  lastmod: false

  # show reading time
  readingTime: true

  # show word count
  wordCount: true

  # Show table of contents, You can enable it separately in the page
  toc:
    enabled: true
    wordCount: 400

  pjax: true
  pwa: true
  katex: true
  backtop: true
  featuredImageHeight: "42%" #42% | false
  defaultFeaturedImage: false

  imageProcessing:
    cover: true
    content: true
    autoResize:
      - 1080
      - 1440
    webp: true

  opengraph:
    twitter:
      cardType: summary_large_image # summary | summary_large_image
      site: "@davesaah_"
    image: "featured.png" # in assets folder | false

  author: Hesed
  keywords:
    - Faith
    - Hope
    - Love
  description: "Broadcasts from Mount Zion"

build:
  noJSConfigInAssets: true

languages:
  en-us:
    contentDir: content

staticDir:
  - static
